### PR TITLE
Coop description & public address/contact info

### PR DESCRIPTION
**Pull request by nick-hou**
Addresses #36, #37, #147 

I was able to run "python manage.py makemigrations directory" and get a migration file, but ran into the same issue as before of not being able to modify a many-to-many relation. Changed it to a remove and add operation and was able to run the migration. I don't think this migration would delete any existing data/models but definitely let me know if something looks off

### CODE REVIEW

**Review by davealvaradodignifi — APPROVED** [review]
I'm a little slow to respond but great solution!  I see no drawbacks.

**Review by laredotornado — APPROVED** [review]

**Comment by nick-hou** [comment]
Hey @laredotornado, have you had any issues running the app since this was merged? 

Not sure why it didn't come up when I was working on this PR, but I just tried to run docker-compose up and was getting a "conflicting migrations detected; multiple leaf nodes in the migration graph" error. Somehow the migration I generated just ignored the previous one and created overlapping dependencies.

I've got a fix locally that I can push, if this is happening to you as well.

**Comment by laredotornado** [comment]
I did get that error as well but checked a fix in.  If you pull the latest
you should see it (it likely mirrors the fix you have locally).

**Comment by nick-hou** [comment]
Here's what I did, your commands probably did the same thing but just a sanity check:
- renamed 'migrations/**0006**_auto_20220120_1940' to '**0007**_auto_20220120_1940'
- Changed the dependency in line 11 of 0007_auto... from `('directory', '0005_coop_approved')` to `'0006_alter_coop_approved'`

**Pull request merged**
