### PR TITLE
Feature/251 directory add update form update

### PR DESCRIPTION
**Pull request by domdelorenzo**

### CODE REVIEW

**Review by now-is — APPROVED** [review]
Appreciate the consistent and tidy formatting!

**Review by now-is — APPROVED** [review]
Incredibly finicky stuff, but for what it's worth:

1. vars that are never used:

setContactEmailPublic: line 95
setContactPhonePublic: line 98
getErrors: line 113
result: line 411

2. switch is missing a default case: line 250

3. useEffects have more "dependencies" than specified:

useEffect line 427: fetchCoopForUpdate id location.pathname
useEffect line 473: checkExistingEntity location.pathname
useEffect line 480: checkRequired

**Review by now-is — APPROVED** [review]

**Review by now-is — APPROVED** [review]
Finicky: useState need not be imported, all its mentions are commented out.

**Comment by domdelorenzo** [comment]
@now-is - thanks for the review! Just pushed an update to remove the unused variables and import. I'm not going to touch the useEffects for now just because it's not my code and I don't want to inadvertently trigger additional re-renders. I'd definitely like to look into those at another time though.

**Pull request merged**
